context: baal
contexts:
    baal:
        endpoints:
            - 192.168.10.39
            - 192.168.10.21
            - 192.168.10.22
        nodes:
            - 192.168.10.39
            - 192.168.10.21
            - 192.168.10.22
        ca: ENC[AES256_GCM,data:f90BT+PpHbTnvaX6x5eE2eFixgfeqakl6myJmSE/ldiFMfNfds6Qr2CUSxvSr3YzkaKS2E1nR78SH7tEqmN1isP/sXscbqMEwTowxPAlTrhUiNhOKeUQ/NjV0FEVL2mKtIlpnRY1A5y7S8uSLFyt4mDduI4bExQdGJCbq2OiebxX7t6AxAbXwNPqT2GCFZKPLrLnGSnxBkEzqQU46RDAz9tBBzSFfh0DtPJih9vdep8ydBylUGczFNaMxR+rYdGprQyVPLEwmpxl+EH3f6FkXyBZfLqOoQR+Zhuu7xOXCW7XHMLwZdbhk6/wWr8sP3Dgc8vi2NYWfQCaF+TbvqHCCwLCZOUClricUVRQEPgZVh4Zx5G9Me/RQFmUCvq26H2aiqCsCFmxma/3jVTY2Bb+dYfJotwpUde8I3dAgzoCsucWcdjsJNKjLEmxTf0wF+vgTwDBZJRqw7tXzo837ZwW5HILwUa2GvRXDuKVg1xrD23bECFt7/NteeXM2oJp0nSwGnZwJ1388PBCMp3g1Z8vCAiYAEBmYSZ1m+lM56SeJ72s3/DNDlZ3OizGauwn/0DY/ENWNXCvjdH3WVYEd1zhVvk+phWRkQWmP7Ff2s0ZBivaDwUvTmaxNqQSAfuu+yoiV8hh1ZXjI3dsoRzdCfxCaBUWv7Zm7dy+pMl/TmqyvEvYh6+n60wOYhy/uvwQ6BHTzcZUvbkzFqPa6g+fUujqVZlnZlwHxnN/KlCvFVk49bSEBqmNy2dQxAYQ50oCmWm0jK7gmJZdfXePlPBDk1hzXcAttFMkmPfz693pbqCHinMcuveanlYcd56YhGIq51MuvGiDn6k46GpOf3vXaxUJK68p0Z5k/vo3yoClOZOJ9F8S/Z4m,iv:G+SOzf/04NZtYPudNknN7EBRIILocZsS9wtxFtNObOo=,tag:2voUO4/Zbw7VhQ38mAiXpg==,type:str]
        crt: ENC[AES256_GCM,data:FEh70pnsJqbPVebYFwKhhT89RAhwkns9uFnsITluV/l2eXmQIaGz6YO541ggZUOc6dMeoXrjLKlSAWldvDlKhOhC6dG/o/Mu+hmXKTOXLi690brhHpd6Apng9zgJuiTzqaavf4JRCB4xdqGB2lLWmBEQD69R+TYNza2Gg61MZrf9bxp6Mn07TvtUcCktxuJb07qCCs1UlK3MKEgtabr+Lyh21sJmla9ujse9Mca3yXhuB934RvwuWkde1QAUrB+RqOujbCB5EBeFdhSYDsUJukqjio1qlmhLIpB8raw/goV47XbhSAtxob95PHpxmmHFKZcuuGglhRho+igsgcs7MXczjFoJT2BJzTIZUlO7QZ0uji8UcqjmazpT86rhrsCGDEHcjKLX4p3Kzr79XtIlw6C9Kp5+gw8OPlWEtB4lGyOZBxE+5ISkb7U6IgxpEPBjKkCcn5lRZDiR/AtTORUL9xggdDyHtLQ9iGyhc8vtanbBoRJXgiEvAKGoWi3Z8nJEQ5gyXNj+vZaUQkYGabS2t2tGrVyuEeGtSkN6zYFtoJrB+7tD8IWltEHjGtlsYnlsXifwb7ik3ZnYRINzzaG151/q7RFpjtMs7XL+eUPEeN2Cyyv1XuuMFlOYcZ9WxctFHPf7/w0t33D3exdLl8/hfQHv5Pcw1AwnxLMP0an7LEbgIj8PpQZVkRvQP/skZKtiP32GMvvQi28PsyiHdE7x6xqf2T0hN25nu+uBiCBCbFL8rKrWUdZDK74myPUYcFIb3j7uZm+J03IOHsLGIEg8mKfl540lF/VMkXvf4e9jq9Z7eaDl3Q57sM/a7Pg=,iv:61hMeKwZiz/cIjjazsveEwpYrFaOBknKfSFSDKiZGcE=,tag:gKKFSzxY00UKS0Og2f1zJw==,type:str]
        key: ENC[AES256_GCM,data:+WllyEGYaZ6Ju609HEZVuuyUJ1auq7HOkuPh3z5MoukVyqf0f/IFe++f6l4QvUs/cpqByRtMnyw0CSIJAur1qmKOf9ZMDxKtIF+qLd9tbDkBTJwwZniDWy+K3DAtjKm0kD0vYQKRlTC0w9GJJkxFfP9BcrZOBfX5BABtDbrDSISK6OM3dM0XaB8lbC92+uue7zJ30NJWdJsHODplU4nnfrskXlLhD3goB4cwAxaSTm6pia1K,iv:H7XzjqjxTGzmJrYvCNQeJ1PXfd8HCr7/5a5ov6zMtHA=,tag:9GHnqnQ/V/O7FK0mb3et8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-15T06:14:50Z"
    mac: ENC[AES256_GCM,data:rljMH6f/575+2FaGtB5esoQtJmpISl8vSyNKkBKWOR6cDLjcnq2zqeXcZOqxqyCPc6JkG46djhqvxk+qM9jk26SqDV3OZ97NqFI3CzYuMwT13gilqc29pQZa5yzix7a7CQydEohdqnrH6hlf/dovP5nBVsLpTaAFwhLerIs0l0k=,iv:dm4US4zzlbcXp/PzRBu8+y8qRWG4JrSnl+4d/3ms8Ko=,tag:8p4Y7wGiiMybHvxfvpqs8g==,type:str]
    pgp:
        - created_at: "2024-06-15T06:14:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdTlNmXPjrfYSAQdA0RNzbaKZqgrYhp3Cj2RLaDnEWSuzvqPaoQjTo3VVnjYw
            42kGUAS+pkjPE9uZZM7Wc+GM4L2HSb4AvoysA/wEOOVTa9K4VfXNYDooBlVwYBU2
            0l4BoBrWD6qs5s/fgbTQ3BeSznREQ0vWMToOTfhOYVoZqBS0U1Pv+JmcuGt/Wigj
            nbiP1hxKBn4oBVufopiKuG4vVkvrFysTkYoS6DEKhwFvF2NQwnqaQ3k2Ll4qeeMh
            =8T//
            -----END PGP MESSAGE-----
          fp: 75394D9973E3ADF6
    encrypted_regex: .*(data|ca|ce?rt|key|id|secret).*
    version: 3.8.1
